spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, datasource, aws"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto:  create
    generate-ddl: true

  jwt:
    secretKey: "er2wqe43w234qw2342rwer32erwe234234er23we3we3re3e3e3rw342r4w2r4q4r4q1wre421rqr4212q1re432e4"
    access:
      expiration: 3600000
      header: Authorization
    refresh:
      expiration: 1209600000
      header: Authorization-refresh
